# Generated by Django 2.2.3 on 2020-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201124_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profilePic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
